
$('#sparkline15').sparkline([22, 50, 44, 55, 65,80, ], {
type: 'line',
width: '100%',
height: '150',
chartRangeMax: 50,
resize: true,
lineColor: '#3550c2',
fillColor: '#2a61fa',
highlightLineColor: 'rgba(0,0,0,.1)',
highlightSpotColor: 'rgba(0,0,0,.2)',
});

$('#sparkline16').sparkline([0, 10, 80, 50, 60, 70], {
type: 'line',
width: '100%',
height: '150',
chartRangeMax: 50,
resize: true,
lineColor: '#f86947',
fillColor: '#a83591',
highlightLineColor: 'rgba(0,0,0,.1)',
highlightSpotColor: 'rgba(0,0,0,.2)',
});

$('#sparkline17').sparkline([0, 50, 40, 60, 80], {
type: 'line',
width: '100%',
height: '150',
chartRangeMax: 50,
resize: true,
lineColor: '#7c48f6',
fillColor: '#7b29b7',
highlightLineColor: 'rgba(255,255,255,.5)',
highlightSpotColor: 'rgba(255,255,255,.5)',
});
 
 


